# Generated by Django 2.2 on 2019-04-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='date goal was set')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_bool', models.BooleanField(verbose_name=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Goals')),
            ],
        ),
    ]
