# Generated by Django 2.2 on 2019-04-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice_bool',
            new_name='hal',
        ),
        migrations.AddField(
            model_name='choices',
            name='budget',
            field=models.FloatField(default=1000),
        ),
    ]
